export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_DELETING_ITEM = 'SET_DELETING_ITEM';
export const PRODUCT_REMOVED = 'PRODUCT_REMOVED';
export const PRODUCT_RECEIVED = 'PRODUCT_RECEIVED';
export const PRODUCT_DETAILS_LOADED = 'PRODUCT_DETAILS_LOADED';
export const SET_PRODUCTID = 'SET_PRODUCTID';
export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const GET_NUMBERS_BASKET = 'GET_NUMBERS_BASKET';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const LOGOUT = 'LOGOUT';


